name: Porduction pipeline 

on:
  push:
    branches: [ master ]

jobs:
  build-n-deploy:
    name: Build and deploy to production
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: go test -v ./tests
      env:
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_URL: ${{ secrets.DB_URL }}
